#!/bin/sh

# only private key for now
fail=0

check_input() {
  var=$1
  data=$2
  if [ -z "$data" ]
    then
      echo "Need to specify $var"
      read -p "$var: " data
      if [ -z "$data" ]
        then
          fail=1
      fi
  fi
  eval "$var=$data"
}

check_input "key" $1
check_input "user" $2
check_input "host" $3

echo "Specify host nick-name, use host if not supplied"
read -p '(optional) sshname: ' sshname
if [ -z "$sshname" ]
then
  sshname=$host
fi

if [ "$fail" == 1 ] ; then
  echo "exiting script"
  exit 1
fi


#check if key has .pub at the end. For now, make that in assumption.

comm="cat ${key}.pub | ssh ${user}@${host} \"mkdir -p ~/.ssh/ && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys ** chmod 600 ~/.ssh/authorized_keys\""
echo $comm
eval $comm

# Add to ~/.ssh/config file
config_string="\nhost $sshname\n
\t\thostname $host\n
\t\tIdentityFile $key\n
\t\tuser $user\n
\t\tforwardx11 yes
"
#echo $config_string
echo $config_string >> ~/.ssh/config

